website/__init__.py
from flask import Flask, render_template_string, request
from flask_flatpages import FlatPages
from flask_flatpages.utils import pygmented_markdown
from flask.ext.images import Images

def jinja_renderer(text):
  prerendered_body = render_template_string(text)
  return pygmented_markdown(prerendered_body)

app = Flask(__name__)

# Default Values for config
app.config['SECTION_MAX_LINKS'] = 10
app.config['FLATPAGES_HTML_RENDERE'] = jinja_renderer
app.config.from_object('config')
flatpages = FlatPages(app)
images = Images(app)

from website.views import general
from website.views import pages

app.register_blueprint(general.mod)
app.register_blueprint(pages.mod)

@app.context_processor
def context_data():
  def is_active(endpoint=None, section=None, noclass=False):
    rtn = ""
    if noclass:
      rtn = 'active'
    else:
      rtn = 'class=active'
    if endpoint and section:
      if 'section' in request.view_args:
        if request.url_rule.endpoint == endpoint and request.view_args['section'] == section:
          return rtn
    elif endpoint:
      return rtn if request.url_rule.endpoint == endpoint else ''
    elif section:
      if 'section' in request.view_args:
        return rtn if request.view_args['section'] == section else ''
      elif 'path' in request.view_args:
        return rtn if request.view_args['path'].split('/')[0] == section else ''
    return ''
  def subsections(section):
    return pages.get_subsections(flatpages, section)
  def prettify(link_text):
    return link_text.replace('-', ' ').title()
  return dict(is_active=is_active,
              debug=app.debug,
              sections=pages.get_sections(flatpages),
              prettify=prettify,
              subsections=subsections)

website/views/general.py
from website import app
from flask import Blueprint, render_template, session, redirect, url_for, \
        request, abort

mod = Blueprint('general', __name__)

@mod.route('/contact')
def contact(name=None):
  return render_template('general/contact.html', name=name)

website/views/pages.py
from datetime import date, datetime
from website import app
from flask import Blueprint, render_template, session, redirect, url_for, \
        request, abort
from flask_flatpages import FlatPages
from random import sample
import os

mod = Blueprint('pages', __name__)
pages = FlatPages(app)

def get_pages(pages, offset=None, limit=None, section=None, subsection=None, year=None, before=None, after=None):
  """ Retrieves pages that match specific criteria
  """
  things = list(pages)
  # Assign section if one is not set in the page
  for thing in things:
    if not thing.meta.get('section'):
      thing.meta['section'] = thing.path.split('/')[0]
    if not thing.meta.get('subsection'):
      # if subsection isn't set manually, only set it if the path is long enough
      if len(thing.path.split('/')) > 2:
        thing.meta['subsection'] = thing.path.split('/')[1]
  # filter unpublished
  if not app.debug:
    things = [p for p in things if p.meta.get('published') is True]
  # filter section
  if section:
    things = [p for p in things if p.meta.get('section') == section]
  if subsection:
    things = [p for p in things if p.meta.get('subsection') == subsection]
  # filter year
  if year:
    things = [p for p in things if p.meta.get('date').year == year]
  if before:
    things = [p for p in things if p.meta.get('date') < before]
  if after:
    things = [p for p in things if p.meta.get('date') > after]
  # sort what's left by date
  things = sorted(things, reverse=True, key=lambda p: p.meta.get('date', date.today()))
  # assign prev/next in series
  for i, thing in enumerate(things):
    if i != 0:
      if section and things[i - 1].meta.get('section') == section:
        thing.next = things[i - 1]
    if i != len(things) - 1:
      if section and things[i +1].meta.get('section') == section:
        thing.prev = things[i +1]
  # offset and limit
  if offset and limit:
    return things[offset:limit]
  elif limit:
    return things[:limit]
  elif offset:
    return things[offset:]
  else:
    return things

def get_sections(pages):
  things = list(pages)
  for thing in things:
    if not thing.meta.get('section'):
      thing.meta['section'] = thing.path.split('/')[0]
  return sorted(list(set([thing.meta.get('section') for thing in things])))

def get_subsections(pages, section):
  pages = list(get_pages(pages, section=section))
  things = []
  for page in pages:
    if not page.meta.get('subsection'):
      if len(page.path.split('/')) > 2:
        page.meta['subsection'] = page.path.split('/')[1]
        things.append(page)
    else:
      things.append(page)
  return sorted(list(set([thing.meta.get('subsection') for thing in things])))

def get_years(pages):
  years = list(set([page.meta.get('date').year for page in pages]))
  years.reverse()
  return years

def section_exists(section):
  return not len(get_pages(pages, section=section)) == 0
def subsection_exists(section, subsection):
  return not len(get_pages(pages, section=section, subsection=subsection)) == 0

@mod.route('/<path:path>/')
def page(path):
  section = path.split('/')[0]
  page = pages.get_or_404(path)
  # ensure an accurate "section" meta is available
  page.meta['section'] = page.meta.get('section', section)
  # show all pages in debug, but hide unpublished in production
  if not app.debug and not page.meta.get('published', False):
    abort(404)
  templates = []
  templates.append(page.meta.get('template', '%s/page.html' % section))
  templates.append('default_templates/page.html')

  rtn_images = []
  if os.path.isdir(os.path.join(app.static_folder, 'images', path)):
    raw_images = os.listdir(os.path.join(app.static_folder, 'images', path))
    if not page.meta.get('all_images', False):
      if len(raw_images) > 3:
        choices = sample(raw_images, 3)
      else:
        choices = raw_images
      for raw_image in choices:
        # Flask-Images already knows to look in the static folder, so only include the rest
        rtn_images.append(os.path.join('images', path, raw_image))
    else:
      for raw_image in raw_images:
        rtn_images.append(os.path.join('images', path, raw_image))
  return render_template(templates, page=page, section=section, images=rtn_images)

@mod.route('/<string:section>/')
def section(section):
  if not section_exists(section):
    abort(404)
  templates = []
  templates.append('%s/index.html' % section)
  templates.append('default_templates/index.html')
  things = get_pages(pages, limit=app.config['SECTION_MAX_LINKS'], section=section)
  years = get_years(get_pages(pages, section=section))
  return render_template(templates, pages=things, section=section, years=years)

@mod.route('/<string:section>/<string:subsection>')
def subsection(section, subsection):
  if not section_exists(section):
    abort(404)
  if not subsection_exists(section, subsection):
    abort(404)
  templates = []
  templates.append('%s/index.html' % section)
  templates.append('default_templates/index.html')
  things = get_pages(pages, limit=app.config['SECTION_MAX_LINKS'], section=section, subsection=subsection)
  years = get_years(get_pages(pages, section=section, subsection=subsection))
  return render_template(templates, pages=things, section=section, subsection=subsection, years=years)

@mod.route('/<string:section>/upcoming/')
def section_upcoming(section):
  if not section_exists(section):
    abort(404)
  templates = []
  templates.append('%s/upcoming.html' % section)
  templates.append('default_templates/upcoming.html')
  things = get_pages(pages, section=section, after=date.today())
  years = get_years(get_pages(pages, section=section))
  return render_template(templates, pages=things, section=section, years=years)

@mod.route('/<string:section>/past/')
def section_past(section):
  if not section_exists(section):
    abort(404)
  templates = []
  templates.append('%s/past.html' % section)
  templates.append('default_templates/past.html')
  things = get_pages(pages, section=section, before=date.today())
  years = get_years(get_pages(pages, section=section))
  return render_template(templates, pages=things, section=section, years=years)

@mod.route('/<string:section>/<int:year>/')
def section_archives_year(section, year):
  if not section_exists(section):
    abort(404)
  templates = []
  templates.append('%s/archives.html' % section)
  templates.append('default_templates/archives.html')
  years = get_years(get_pages(pages, section=section))
  things = get_pages(pages, section=section, year=year)
  return render_template(templates, pages=things, section=section, years=years, year=year)

@mod.route('/')
def all_pages():
  template = 'general/index.html'
  things = get_pages(pages, limit=app.config['SECTION_MAX_LINKS'])
  years = get_years(get_pages(pages))
  return render_template(template, pages=things, years=years)

website/templates/_list.html
<div class="row">
    {%- for page in pages %}
    <div class="well {% if not page.published %}unpublished{% endif %}">
        <h2>
            <a href="{{ url_for('pages.page', path=page.path) }}">{{ page.title }}</a>
            | <time datetime="{{ page.date }}">{{ page.date }}</time>
        </h2>
        <q itemprop="description">
            {%- if page.meta.summary and page.meta.summary|striptags|trim %}
                {{- page.summary|trim }}
            {%- elif page.html|striptags|trim -%}
                {{- page.html|striptags|trim|truncate(135) }}
            {%- endif -%}
        </q>
        <hr>
    </div>
    {%- else %}
      <div>No pages (yet?)</div>
    {%- endfor %}
</div>

website/templates/base.html
<!DOCTYPE html>
<html lang='en'>

  <head>

    <!-- Pull in all the CSS and JS scripts -->
    {% include 'layouts/head.html' with context %}

    <!-- Allow inline CSS from child page -->
    <style>
      {% block style %}{% endblock style %}
    </style>

    <!-- Pull title from each page if it exists -->
    <title>
      {% block title %}Ramblings{% endblock title %}
    </title> 

  </head>

  <body>

  <!-- Get the <header> data -->
  {% include 'layouts/header.html' %}

  <!-- Main DIV -->
  <div class="container-fluid text-center">
    <div class="row">

      <!-- Pull in the Progress bars and Left Column -->
      {% include 'layouts/left_col.html' %} 

      <!-- Central Content DIV -->
      <div class="col-sm-7 text-left" >
        <!-- Central ALERT Text -->
        {% block alert %}{% endblock alert %}

        <!-- CONTENT PAGE TITLE -->
        {% if self.pagetitle() %}
        <div class="row">
          <div class="col-sm-12 text-center">
            <h1>{% block pagetitle %}{% endblock pagetitle %}</h1> 
          </div>
        </div>
        {% endif %}

        <!-- Get the Main Content -->
        {% block content %}
          Default content
        {% endblock content %}

        <!-- Pagination -->
        {% include 'layouts/central-pagination.html' %}

      <!-- END Central Content DIV -->
      </div>
   
      <!-- Social Media / Right Column --> 
      {% include 'layouts/right_col.html' %}

    <!-- END Main DIV -->
    </div>
    <!-- Gallery Modal -->
    {% include 'layouts/gallery.html' %}
  </div>

  <!-- get the <footer> -->
  {% include 'layouts/footer.html' %} 
  {% include 'layouts/js_bottom.html' %}
  </body>
</html>

website/templates/blog/archives.html
{% extends 'blog/base.html' %}
{% block title %}Blog Archives{% endblock %}
{% block content %}
<h3>Events in {{ year }}</h3>
{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item" href="{{ url_for('pages.section', section=section) }}">Back to {{ section }}</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>
{% endif %}
{% endblock %}

website/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Ramblings of a mad man{% endblock %}
{% block content %}
<h3> Latest Posts</h3>
{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item disabled" href="#">Browse {{ section }} archives</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>
{% endif %}

{% endblock %}

website/templates/blog/page.html
{% extends 'blog/base.html' %}

{% if page.title %}
  {% block title %}
    {{ page.title }}
  {% endblock title %}
{% endif %}

{% if page.alert %}
  {% block alert %}
    {{ page.alert }}
  {% endblock alert %}
{% endif %}

{% if page.pagetitle %}
  {% block pagetitle %}
    {% if page.date %}
      {{ page.pagetitle }} - {{ page.date }}
    {% else %}
      {{ page.pagetitle }}
    {% endif %}
  {% endblock pagetitle %}
{% endif %}

<!-- Get the Main Content -->
{% block content %}
<div class="row well">
  {{  page }}
</div>
{% if images %}
<div class="row text-center">
{% for image in images %}
  <div class="col-sm-4 text-center">
    <img class="img-responsive well" src="{{ url_for('images.fit', filename=image, width=400) }}" />
  </div>
{% endfor %}
</div>
{% endif %}
  {% if page.prev -%}
  <a class="prev" href="{{ url_for("pages.page", path=page.prev.path) }}">&lt;&lt; {{ page.prev.title }} - {{page.prev.date}}</a>
  {%- endif %}
  {% if page.prev and page.next %} | {% endif %}
  {% if page.next -%}
  <a class="next" href="{{ url_for("pages.page", path=page.next.path) }}">{{ page.next.title }} - {{page.next.date}} &gt;&gt;</a>
  {%- endif %} 
{% endblock content %}

website/templates/default_templates/archives.html
{% extends 'default_templates/base.html' %}
{% block title %}Archives{% endblock %}
{% block content %}
<h3>Events in {{ year }}</h3>
{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item" href="{{ url_for('pages.section', section=section) }}">Back to {{ section }}</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>
{% endif %}
{% endblock %}

website/templates/default_templates/base.html
{% extends 'base.html' %}

{% block page_title %}{% endblock page_title %}
{% block title %}{% endblock title %}
{% block section %}default{% endblock section %}

website/templates/default_templates/index.html
{% extends 'default_templates/base.html' %}
{% block title %}Ramblings of a mad man{% endblock %}
{% block left_col %}
  {% for subsection in subsections(section) %}
    <div class="well">
      <a href="{{ url_for('pages.subsection', section=section, subsection=subsection) }}">{{prettify(subsection)}}</a>
    </div>
  {% endfor %}
{% endblock left_col %}

{% block content %}
<h3> Latest Posts</h3>
{% include "_list.html" %}
{% if years|length %}
  <div class="row">
    <div class="col-sm-5"></div>
  <div class="col-sm-2 list-group">
    <a class="list-group-item disabled" href="#">Browse {{ section }} archives</a>
    {% with current_year = year %}
      {% for year in years %}
        {% if current_year == year %}
            <a class="list-group-item active" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% else %}
          <a class="list-group-item" href="{{ url_for('pages.section_archives_year', section=section, year=year) }}">{{ year }}</a>
        {% endif %}
      {% endfor %}
    {% endwith %}
  </div>
  <div class="col-sm-5"></div>
  </div>
{% endif %}

{% endblock %}

website/templates/default_templates/page.html
{% extends 'default_templates/base.html' %}

{% if page.title %}
  {% block title %}
    {{ page.title }}
  {% endblock title %}
{% endif %}

{% if page.alert %}
  {% block alert %}
    {{ page.alert }}
  {% endblock alert %}
{% endif %}

{% if page.pagetitle %}
  {% block pagetitle %}
    {% if page.date %}
      {{ page.pagetitle }} - {{ page.date }}
    {% else %}
      {{ page.pagetitle }}
    {% endif %}
  {% endblock pagetitle %}
{% endif %}

<!-- Get the Main Content -->
{% block content %}
<div class="row well">
  {{  page }}
</div>
{% if images %}
<div class="row text-center" id="links">
{% for image in images %}
  <div class="col-lg-3 col-sm-4 col-xs-6 text-center">
    <a href="{{ url_for('images.fit', filename=image, width=2048) }}" data-gallery>
      <img class="img-responsive well" src="{{ url_for('images.fit', filename=image, width=400) }}" />
    </a>
  </div>
{% endfor %}
</div>
{% endif %}
  {% if page.prev -%}
  <a class="prev" href="{{ url_for("pages.page", path=page.prev.path) }}">&lt;&lt; {{ page.prev.title }} - {{page.prev.date}}</a>
  {%- endif %}
  {% if page.prev and page.next %} | {% endif %}
  {% if page.next -%}
  <a class="next" href="{{ url_for("pages.page", path=page.next.path) }}">{{ page.next.title }} - {{page.next.date}} &gt;&gt;</a>
  {%- endif %} 
{% endblock content %}

website/templates/general/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us{% endblock %}
{% block content %}
  <h3>Email</h3>
  <p>Email siebren (at) siebrenbakker.com</p>
{% endblock %}

website/templates/general/index.html
{% extends 'base.html' %}
{% block title %}Ramblings of a mad man{% endblock %}
{% block content %}
<h3> Latest Things</h3>
{% include "_list.html" %}
{% endblock %}

website/templates/layouts/central-alert.html
      <!-- ALERT Message -->
          <!-- <p><strong><span style="color: black;text-size:120%">Hey! Listen!</span></strong></p> -->
          <!-- <p><span style="color: black;">We just passed $15,000 raised!</span></p> -->

      <div class="alert alert-info fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
         <h1>Hey! Listen!</h1>
         <h4>We just passed $16,000 raised!</h4>
      </div>

website/templates/layouts/central-pagination.html
        <!-- Placeholder for testing 
        <div class="row">
            <ul class="pagination pagination-sm">
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            </ul>
        </div>
        -->

website/templates/layouts/central-title.html
      <!-- CONTENT TITLE -->
      <div class="row">
        <div class="col-sm-12 contentborder-yellow">
          <!-- <p>Status Box</p> -->
          {% block pagetitle %}{% endblock %}
          <!-- <h1>Current Events</h1> -->
        </div>
      </div>

website/templates/layouts/footer.html
  <footer style="margin-left:10px;margin-right:10px;">
    &copy; Siebren Bakker 2016
    <a style="float:right;" href="https://twitter.com/aevumdecessus" target="_blank">@aevumdecessus</a>
  </footer>

  {% if not debug %}
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-76958333-1', 'auto');
    ga('send', 'pageview');
  </script>
  {% endif %}

website/templates/layouts/gallery.html
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery" data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

website/templates/layouts/head.html
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro|Press+Start+2P|Roboto+Slab:300' rel='stylesheet' type='text/css'>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/b7db31fc4c.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Blueimp Gallery -->
    <link rel='stylesheet' href="{{ url_for('static', filename='css/blueimp-gallery.min.css') }}" />
    <link rel='stylesheet' href="{{ url_for('static', filename='css/bootstrap-image-gallery.min.css') }}" />

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">

    <!-- Customized CSS -->
    <link rel='stylesheet' href="{{ url_for('static', filename='css/main.css') }}" />

website/templates/layouts/header.html
<!-- Bootstrap Navbar -->
  <header>
    <nav class="navbar navbar-inverse">

      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Siebren Bakker</a>
        </div>

        <div class="collapse navbar-collapse navbar-left" id="myNavbar">
          <ul class="nav navbar-nav">
            <li {{is_active('pages.all_pages')}}><a href="{{ url_for('pages.all_pages') }}">home</a></li>
            <li {{is_active('general.contact')}}><a href="{{ url_for('general.contact') }}">contact</a></li>
            {% for section in sections %}
              <li {{is_active(section=section)}}><a href="{{url_for('pages.section', section=section)}}">{{section}}</a></li>
            {% endfor %}
          </ul>
        </div> 


        <!-- Social Media Buttons -->
        <div class="collapse navbar-collapse navbar-right" id="mySocial">
          <ul class="nav navbar-nav navbar-right social">
            <li><a class="fa fa-twitter fa-lg" href="https://twitter.com/aevumdecessus" target="_blank"></a> </li>
            <li><a class="fa fa-twitch fa-lg" href="https://www.twitch.tv/aevumdecessus" target="_blank"></a></li>
            <li><a class="fa fa-github fa-lg" href="https://github.com/aevumdecessus" target="_blank"></a></li>
            <li><a class="fa fa-google-plus-official fa-lg" href="https://plus.google.com/+SiebrenBakker/posts" target="_blank"></a></li>
          </ul>
        </div>
  
      </div>

    </nav>
  </header>

website/templates/layouts/js_bottom.html
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<!-- Blueimp Bootstrap Image Gallery -->
<script src="{{ url_for('static', filename='js/jquery.blueimp-gallery.min.js') }}" ></script>
<script src="{{ url_for('static', filename='js/bootstrap-image-gallery.min.js') }}" ></script>

website/templates/layouts/labels.html
        <!-- LABELS -->
        <div class="well well-sm">
          <p>Labels</p>
          <span class="label label-default">Default</span>
          <span class="label label-primary">Primary</span>
          <span class="label label-success">Success</span>
          <span class="label label-info">Info</span>
          <span class="label label-warning">Warning</span>
          <span class="label label-danger">Danger</span>
        </div>

        <!-- SUPPORTERS -->
        <div class="well well-sm">
          <p>Our Supporters</p>
        </div>

      </div>  <!-- Closing Left col-sm-2 -->

website/templates/layouts/left_col.html
<!-- LEFT HAND COLUMN -->
<div class="col-sm-2">
  
</div>  <!-- Closing Left col-sm-2 -->

website/templates/layouts/right_col.html
<div class="col-sm-3">
  {%block rightcol %}{% endblock rightcol %}
</div>

website/templates/layouts/rightcol.html
<div class="col-sm-3">
  {%block rightcol %}{% endblock rightcol %}
</div>